// <auto-generated />
namespace Pharmacy_Online.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedproductmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedproductmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201711272143301_updated product model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
